server:
  port: 9000

spring:
  main:
    banner-mode: off
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:mydb
    username: root
    password: root
    driverClassName: org.h2.Driver
  h2:
    console:
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false
